// features/rooms/roomData.js
export const roomDetails = [
    {
      id: "1",
      hotelId: "1",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Suite Presidencial",
      description: "Habitación de lujo con vista al mar y jacuzzi.",
      capacity: 2,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "2",
      hotelId: "1",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Habitación Deluxe",
      description: "Habitación espaciosa con balcón privado.",
      price: 300,
      capacity: 2,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "3",
      hotelId: "1",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Habitación Económica",
      description: "Habitación cómoda y accesible.",
      price: 100,
      capacity: 1,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "1",
      hotelId: "3",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Suite Presidencial",
      description: "Habitación de lujo con vista al mar y jacuzzi.",
      price: 500,
      capacity: 2,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "2",
      hotelId: "3",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Habitación Deluxe",
      description: "Habitación espaciosa con balcón privado.",
      price: 300,
      capacity: 2,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "3",
      hotelId: "4",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Habitación Económica",
      description: "Habitación cómoda y accesible.",
      price: 100,
      capacity: 1,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "1",
      hotelId: "5",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Suite Presidencial",
      description: "Habitación de lujo con vista al mar y jacuzzi.",
      price: 500,
      capacity: 2,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "2",
      hotelId: "7",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Habitación Deluxe",
      description: "Habitación espaciosa con balcón privado.",
      price: 300,
      capacity: 2,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "3",
      hotelId: "6",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Habitación Económica",
      description: "Habitación cómoda y accesible.",
      price: 100,
      capacity: 1,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "1",
      hotelId: "7",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Suite Presidencial",
      description: "Habitación de lujo con vista al mar y jacuzzi.",
      price: 500,
      capacity: 2,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "2",
      hotelId: "6",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Habitación Deluxe",
      description: "Habitación espaciosa con balcón privado.",
      price: 300,
      capacity: 2,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "3",
      hotelId: "8",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Habitación Económica",
      description: "Habitación cómoda y accesible.",
      price: 100,
      capacity: 1,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "1",
      hotelId: "8",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Suite Presidencial",
      description: "Habitación de lujo con vista al mar y jacuzzi.",
      price: 500,
      capacity: 2,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "2",
      hotelId: "8",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Habitación Deluxe",
      description: "Habitación espaciosa con balcón privado.",
      price: 300,
      capacity: 2,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    {
      id: "3",
      hotelId: "9",
      image: "https://media.istockphoto.com/id/1467126728/es/foto/dise%C3%B1o-interior-de-dormitorio-moderno-escandinavo-y-japon%C3%A9sdi-con-cama-color-blanco-mesa-y.jpg?s=612x612&w=0&k=20&c=-B23X_0Qnt8RnFvsGJa7PFKuDL0cskPhNBPdSIGuoYg=",
      name: "Habitación Económica",
      description: "Habitación cómoda y accesible.",
      price: 100,
      capacity: 1,
      rating: "9.0",
      location: "El Poblado, Medellín · 2,6 km del centro",
      roomType: "Estudio Familiar",
      roomDetails: "Estudio entero · 1 baño · 1 cocina · 38 m²",
      beds: "2 camas (1 sofá cama, 1 doble grande)",
      benefits: ["Desayuno incluido", "Cancelación gratis"],
      warning: "Solo queda 1 a este precio en nuestra web",
      oldPrice: "COP 3.472.360",
      price: "COP 3.192.740",
      taxes: "+ COP 606.620 de impuestos y cargos"
    },
    // Añade más habitaciones para otros hoteles
  ];
